name: Local Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # based on https://github.com/bnjbvr/cargo-machete
  machete:
    name: machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@auto-install-action
        
  check-schema-binary-naming:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Check schema binary naming convention
      run: bash scripts/check-schema-naming.sh

  check-schema-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Generate schema
        run: bash scripts/schema.sh
      - name: Check for schema drift
        run: |
          if ! git diff --quiet; then
            echo "❌ Schema is outdated. Please run 'bash scripts/schema.sh' and commit the changes.";
            git diff;
            exit 1;
          fi

  check-proto-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: bufbuild/buf-action@v1
        with:
          # Only install the buf CLI.
          setup_only: true
      - name: Generate proto
        run: bash scripts/protocgen.sh
      - name: Check for schema drift
        run: |
          if ! git diff --quiet -- packages/proto; then
            echo "❌ Protobuf bindings are out-of-date. Run scripts/protocgen.sh and commit the result."
            git --no-pager diff -- packages/proto;
            exit 1;
          fi

  check-go-datagen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Tidy go modules
        run: go mod tidy
        working-directory: ./datagen
      - name: Check datagen
        run: go run datagen/*.go

  local-build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.86.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |
        rustup component add rustfmt clippy
        rustup toolchain install nightly --component rustfmt  # Install nightly rustfmt
    - name: Check format (nightly)
      run: cargo +nightly fmt -- --check
    - name: Check clippy
      run: cargo clippy --workspace --all-features --all-targets -- -D warnings
    - name: Run unit tests
      run: cargo test --lib
